In [ ]:


import pandas as pd

data = {'studyhours': [ 2,3,4,5,6,1,7,8,2,9],
        'sleephours': [ 8,7,6,5,4,10,3,2,9,1],
        ' pass': [0,0,1,1,1,0,1,1,0,1 ]}

df = pd.DataFrame(data)
print(df)

x = df.drop(' pass', axis=1)
y = df[' pass']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

model=LinearRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

accuracy = model.score(x_test, y_test)
print("Accuracy:", accuracy)

new_data = pd.DataFrame({'studyhours': [5], 'sleephours': [7]})
prediction = model.predict(new_data)
print("Prediction:", prediction)


   studyhours  sleephours   pass
0           2           8      0
1           3           7      0
2           4           6      1
3           5           5      1
4           6           4      1
5           1          10      0
6           7           3      1
7           8           2      1
8           2           9      0
9           9           1      1
Accuracy: 0.0
Prediction: [0.12295082]


In [ ]:


import pandas as pd

data = {'studyhours': [ 2,3,4,5,6,1,7,8,2,9],
        'sleephours': [ 8,7,6,5,4,10,3,2,9,1],
        ' pass': [0,0,1,1,1,0,1,1,0,1 ]}

df = pd.DataFrame(data)
print(df)

x = df [ ['studyhours','sleephours']]
y = df[' pass']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

model=LinearRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

accuracy = model.score(x_test, y_test)
print("Accuracy:", accuracy)

new_data = pd.DataFrame({'studyhours': [5], 'sleephours': [7]})
prediction = model.predict(new_data)
print("Prediction:", prediction)


   studyhours  sleephours   pass
0           2           8      0
1           3           7      0
2           4           6      1
3           5           5      1
4           6           4      1
5           1          10      0
6           7           3      1
7           8           2      1
8           2           9      0
9           9           1      1
Accuracy: 0.0
Prediction: [0.12295082]


In [ ]:


import pandas as pd

data = {'studyhours': [ 2,3,4,5,6,1,7,8,2,9],
        'sleephours': [ 8,7,6,5,4,10,3,2,9,1],
        ' pass': [0,0,1,1,1,0,1,1,0,1 ]}

df = pd.DataFrame(data)
print(df)

x = df [ ['studyhours','sleephours']]
y = df[' pass']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)

from sklearn.linear_model import   LogisticRegression
model =   LogisticRegression ()
model.fit(x_train, y_train)

model= LogisticRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

from sklearn.metrics import accuracy_score
accuracy = model.score(x_test, y_test)
print("Accuracy:", accuracy)

new_data = pd.DataFrame({'studyhours': [5], 'sleephours': [7]})
prediction = model.predict(new_data)
print("Prediction:", prediction)



   studyhours  sleephours   pass
0           2           8      0
1           3           7      0
2           4           6      1
3           5           5      1
4           6           4      1
5           1          10      0
6           7           3      1
7           8           2      1
8           2           9      0
9           9           1      1
Accuracy: 0.5
Prediction: [1]


In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier

In [15]:
iris=load_iris()
x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=25)
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [27]:
multi_layer=MLPClassifier(hidden_layer_sizes=(8,8,8),max_iter=1000,random_state=25)

In [28]:
multi_layer.fit(x_train,y_train)

MLPClassifier(hidden_layer_sizes=(8, 8, 8), max_iter=1000, random_state=25)

In [29]:
predict=multi_layer.predict(x_test)

In [30]:
print(predict)

[0 1 2 1 2 1 2 0 1 1 0 0 0 1 0 1 2 2 1 1 1 1 1 0 0 2 1 2 2 0 1 2 2 0 2 1 1
 0 0 0 0 0 0 0 2]


In [32]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [33]:
print(confusion_matrix(y_test,predict))

[[17  0  0]
 [ 0 15  1]
 [ 0  1 11]]
